# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
